### ISSUE TITLE
add new field nombre to campo model

### ISSUE THREAD

**Issue by Japoivvb** [arileccese/DAM2T-M06-UF2-P2-Viticulture_Arianna#4]
1. add nombre attribute to campo model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by arileccese** [comment]
![#4](https://github.com/arileccese/DAM2T-M06-UF2-P2-Viticulture_Arianna/assets/146862213/86649b43-5ce1-4bcf-964d-2bf51e59001e)

**Comment by arileccese** [comment]
![issue #4](https://github.com/arileccese/DAM2T-M06-UF2-P2-Viticulture_Arianna/assets/146862213/f04052fe-38db-4030-8cb5-6235a209f909)

**Comment by arileccese** [comment]
![modelo campo con nueva columna nombre](https://github.com/arileccese/DAM2T-M06-UF2-P2-Viticulture_Arianna/assets/146862213/36233185-1b1e-43fa-b77b-2fca71a5212e)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
