### ISSUE TITLE
update campo_id.vid to null once vendimia is done simulating vid is only linked to bodega

### ISSUE THREAD

**Issue by Japoivvb** [arileccese/DAM2T-M06-UF2-P2-Viticulture_Arianna#5]
1. in vendimia() method update to null values campo_id from vid table

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by arileccese** [comment]
![Asignar a null campo_id cuando la vendimia esté hecha](https://github.com/arileccese/DAM2T-M06-UF2-P2-Viticulture_Arianna/assets/146862213/7f34439c-3b7e-4a9b-bc10-958d4d0d04ad)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
